### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by AramisDuf**
Separated solver choice and problem formulation. Updated example notebooks. Updated tests.

### CODE REVIEW

**Comment by bmeyers** [comment]
@pluflou Could you please take a look at our failing conda build?

**Comment by pluflou** [comment]
@phschiele I see you worked on the recent 1.5 release of CVXPY. Our build is failing when it was previously fine with 1.4.3. Previously we had issues with pybind11 and I had manually added it as a dependency but it doesn't seem to be the issue now (I tried removing it) and there is no error reported during the install. Do you know what could be the issue?

**Comment by phschiele** [comment]
@pluflou Can you pin CVXPY version 1.4.3 to make sure that's actually what's causing the failure? It is not obvious to me from looking at the logs.

**Comment by pluflou** [comment]
@phschiele see runs [#14](https://github.com/cvxgrp/spcqe/actions/runs/9111936854) and [#15](https://github.com/cvxgrp/spcqe/actions/runs/9112012343). If I pin to 1.4.3 _and_ add pybind11 as a runtime dependency it's successful. With 1.5 it fails either way without any install error messages other than "cvxpy is not installed" at test import.

**Comment by pluflou** [comment]
@phschiele @bmeyers  @thistleman I also see this in solar-data-tools when I [reran a previously passing conda build](https://github.com/slacgismo/solar-data-tools/actions/runs/9007682320/job/25069738625) that was installing 1.4.3, now fails with 1.5.1 with the same error
image. 
Not sure if it's our build process or something with cvxpy, still looking into it. If anyone has any clue what could be the issue, please let me know!

**Comment by bmeyers** [comment]
It looks to me like run [#15](https://github.com/cvxgrp/spcqe/actions/runs/9112012343) was successful with cvxpy `1.5.1` installed.

Screenshot 2024-05-16 at 2 05 02 PM

Right?

**Comment by pluflou** [comment]
@bmeyers no that's installing 1.4.3

**Comment by bmeyers** [comment]
Ah yes, I see the distinction now, thank you.

**Comment by pluflou** [comment]
I adjusted the conda recipe with a pin on cvxpy, and added sig-decomp and its dependencies. @AramisDuf some tests are still failing. Let me know when you're ready for a merge.

**Review by bmeyers — APPROVED** [review]

**Pull request merged**
